//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Author { get; set; }
        public override bool Equals(object obj)
        {
            if (obj is book)
            {
                book equaled = (book)obj;
                return (equaled.Author == this.Author)&& (equaled.Price == this.Price) && (equaled.Name == this.Name);
            }
            return false;
        }
    }
}
